name: Deploy to Firebase Hosting on PR
'on': pull_request
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Sets node version and caches .npm folder
      - name: Set node version and cache npm deps
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      # Caches node_modules folder, useful if node version is not going to change
      - name: Cache node modules
        id: node-modules-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/package-lock.json') }}

      # Only install deps if package-lock has changed
      - name: Install deps
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MY_FITNESS_DIARY_59020 }}'
          projectId: my-fitness-diary-59020
